#!/bin/bash

# Navigate to the appropriate working directory if this script was invoked by another script
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

# This calls the uninstaller build target which will build the GIFT uninstaller
./build.sh uninstaller