/**
 * Copyright Dignitas Technologies, LLC
 * 
 * This file and its contents are governed by one or more distribution and
 * copyright statements as described in the LICENSE.txt file distributed with
 * this work.
 */
package mil.arl.gift.sensor.impl.os3d;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.NativeLong;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
@SuppressWarnings("all")
public class DataProcessingInfo extends Structure {

    public NativeLong dwTimeStamp;
    public float fQazimutError_x;
    public float fQazimutError_y;
    public float fQazimutError_z;
    public float fQazimutError_w;
    public float fQerror_x;
    public float fQerror_y;
    public float fQerror_z;
    public float fQerror_w;
    public float fNmagZero;
    public float fNormMag;
    public float fAlfa;
    public NativeLong dwMagneticChannelState;
    // / C type : unsigned long[10]
    public NativeLong[] dwReserved = new NativeLong[10];

    public DataProcessingInfo() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("dwTimeStamp", "fQazimutError_x",
                "fQazimutError_y", "fQazimutError_z", "fQazimutError_w",
                "fQerror_x", "fQerror_y", "fQerror_z", "fQerror_w",
                "fNmagZero", "fNormMag", "fAlfa", "dwMagneticChannelState",
                "dwReserved");
    }

    public static class ByReference extends DataProcessingInfo implements
            Structure.ByReference {

    };

    public static class ByValue extends DataProcessingInfo implements
            Structure.ByValue {

    };

}
